// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnn2VSBEGI030hx7CESyPW6JIn_m1xCqo',
    appId: '1:818268764760:web:d2c01b5807a2c7fe49a82d',
    messagingSenderId: '818268764760',
    projectId: 'questbot-database',
    authDomain: 'questbot-database.firebaseapp.com',
    databaseURL: 'https://questbot-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'questbot-database.firebasestorage.app',
    measurementId: 'G-ZZL4MXL43V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoy6TPJQVt6uo1Ya5R-Fj3DTxpYCzpmbM',
    appId: '1:818268764760:android:af40fc093c0ffe1749a82d',
    messagingSenderId: '818268764760',
    projectId: 'questbot-database',
    databaseURL: 'https://questbot-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'questbot-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5IT-1ohX301XxDcuEH_amZZDhpXW37VY',
    appId: '1:818268764760:ios:264a6b45f9a5d86849a82d',
    messagingSenderId: '818268764760',
    projectId: 'questbot-database',
    databaseURL: 'https://questbot-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'questbot-database.firebasestorage.app',
    iosBundleId: 'com.example.questbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5IT-1ohX301XxDcuEH_amZZDhpXW37VY',
    appId: '1:818268764760:ios:264a6b45f9a5d86849a82d',
    messagingSenderId: '818268764760',
    projectId: 'questbot-database',
    databaseURL: 'https://questbot-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'questbot-database.firebasestorage.app',
    iosBundleId: 'com.example.questbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnn2VSBEGI030hx7CESyPW6JIn_m1xCqo',
    appId: '1:818268764760:web:7dcea8b1819f95ff49a82d',
    messagingSenderId: '818268764760',
    projectId: 'questbot-database',
    authDomain: 'questbot-database.firebaseapp.com',
    databaseURL: 'https://questbot-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'questbot-database.firebasestorage.app',
    measurementId: 'G-0EERWZQB3Y',
  );
}
